version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    container_name: php_nginx_composer_app
    stdin_open: true
    tty: true
    environment:
      - PHP_DISPLAY_ERRORS=1
